/// FANatic Alpha — Strategy Engine
///
/// Decision logic for autonomous World Cup trading agent.
/// Monitors odds shifts from TxLINE feeds and generates trade signals
/// based on sharp movement detection, arbitrage cross-market signals,
/// and time-decay momentum scoring.

use chrono::{DateTime, Utc};
use rust_decimal::prelude::*;
use rust_decimal::Decimal;
use rust_decimal_macros::dec;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use tracing::{debug, info, warn};

// ──────────────────────────────────────────────
// Domain Types
// ──────────────────────────────────────────────

/// Market types available in the TxLINE odds feed for World Cup matches.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MarketType {
    #[serde(rename = "match_winner")]
    MatchWinner,
    #[serde(rename = "total_goals")]
    TotalGoals,
    #[serde(rename = "both_teams_to_score")]
    BothTeamsToScore,
    #[serde(rename = "correct_score")]
    CorrectScore,
    #[serde(rename = "over_under_2_5")]
    OverUnder25,
    #[serde(rename = "asian_handicap")]
    AsianHandicap,
    #[serde(rename = "first_goal_scorer")]
    FirstGoalScorer,
    #[serde(rename = "half_time_full_time")]
    HalfTimeFullTime,
}

impl MarketType {
    /// Returns the minimum odds shift (in basis points) to qualify as "significant"
    /// for this market type. More liquid markets require larger shifts.
    pub fn significance_threshold_bps(&self) -> u32 {
        match self {
            MarketType::MatchWinner => 15,       // 0.15% shift = significant
            MarketType::TotalGoals => 12,
            MarketType::BothTeamsToScore => 18,
            MarketType::CorrectScore => 25,      // thinner, needs bigger move
            MarketType::OverUnder25 => 10,       // very liquid
            MarketType::AsianHandicap => 8,      // extremely liquid
            MarketType::FirstGoalScorer => 30,   // erratic, filter noise
            MarketType::HalfTimeFullTime => 20,
        }
    }
}

/// An individual odds line from the TxLINE feed.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OddsLine {
    pub match_id: String,
    pub market_type: MarketType,
    pub outcome: String,
    pub odds: Decimal,
    pub timestamp: DateTime<Utc>,
    pub bookmaker: String,
    #[serde(default)]
    pub signature: Option<String>,
}

/// Historical snapshot of an odds line for comparison.
#[derive(Debug, Clone)]
pub struct OddsSnapshot {
    pub line: OddsLine,
    pub recorded_at: DateTime<Utc>,
    pub source: String,
}

/// A detected odds shift event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OddsShiftEvent {
    pub match_id: String,
    pub market_type: MarketType,
    pub outcome: String,
    pub previous_odds: Decimal,
    pub current_odds: Decimal,
    pub shift_bps: u32,
    pub direction: ShiftDirection,
    pub detected_at: DateTime<Utc>,
    pub bookmaker: String,
    pub severity: ShiftSeverity,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ShiftDirection {
    #[serde(rename = "up")]
    Up,
    #[serde(rename = "down")]
    Down,
    #[serde(rename = "stable")]
    Stable,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ShiftSeverity {
    #[serde(rename = "minor")]
    Minor,
    #[serde(rename = "notable")]
    Notable,
    #[serde(rename = "significant")]
    Significant,
    #[serde(rename = "critical")]
    Critical,
}

/// A trade signal generated by the strategy engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeSignal {
    pub signal_id: String,
    pub match_id: String,
    pub market_type: MarketType,
    pub outcome: String,
    pub action: TradeAction,
    pub odds: Decimal,
    pub stake_recommendation: Decimal,
    pub confidence: f64,
    pub trigger: SignalTrigger,
    pub generated_at: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
    pub reasoning: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TradeAction {
    #[serde(rename = "back")]
    Back,
    #[serde(rename = "lay")]
    Lay,
    #[serde(rename = "no_action")]
    NoAction,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalConfig {
    /// Minimum odds shift in basis points to trigger a signal.
    pub min_shift_bps: u32,
    /// Maximum stake as a fraction of bankroll.
    pub max_stake_fraction: Decimal,
    /// Signal cooldown in seconds (prevent duplicate signals).
    pub cooldown_secs: u64,
    /// Minimum confidence required to execute.
    pub min_confidence: f64,
    /// Enable cross-market arbitrage detection.
    pub enable_arbitrage: bool,
    /// Momentum window in seconds for trend detection.
    pub momentum_window_secs: u64,
    /// Minimum number of data points for momentum calculation.
    pub momentum_min_samples: usize,
    /// Odds reversal threshold — if odds swing back this many bps within cooldown, flag reversal.
    pub reversal_threshold_bps: u32,
}

impl Default for SignalConfig {
    fn default() -> Self {
        Self {
            min_shift_bps: 10,
            max_stake_fraction: dec!(0.05),
            cooldown_secs: 60,
            min_confidence: 0.65,
            enable_arbitrage: true,
            momentum_window_secs: 300,
            momentum_min_samples: 5,
            reversal_threshold_bps: 20,
        }
    }
}

// ──────────────────────────────────────────────
// Strategy Engine Core
// ──────────────────────────────────────────────

/// The main strategy engine that processes odds data and produces trade signals.
pub struct StrategyEngine {
    config: SignalConfig,
    /// Recent odds snapshots keyed by (match_id, market_type, outcome).
    history: HashMap<String, Vec<OddsSnapshot>>,
    /// Recently emitted signal hashes to enforce cooldown.
    recent_signals: HashMap<String, DateTime<Utc>>,
}

impl StrategyEngine {
    /// Create a new strategy engine with default configuration.
    pub fn new() -> Self {
        Self::with_config(SignalConfig::default())
    }

    /// Create a new strategy engine with custom configuration.
    pub fn with_config(config: SignalConfig) -> Self {
        Self {
            config,
            history: HashMap::new(),
            recent_signals: HashMap::new(),
        }
    }

    /// Build a lookup key for deduplication.
    fn history_key(match_id: &str, market_type: MarketType, outcome: &str) -> String {
        format!("{}|{}|{}", match_id, market_type_string(market_type), outcome)
    }

    /// Ingest a new odds line and check if it generates a trade signal.
    pub fn ingest(&mut self, line: OddsLine) -> Option<TradeSignal> {
        let key = Self::history_key(&line.match_id, line.market_type, &line.outcome);
        let now = line.timestamp;

        // Record this line
        let snapshot = OddsSnapshot {
            line: line.clone(),
            recorded_at: now,
            source: "TxLINE_SSE".into(),
        };

        let previous = self.history.entry(key.clone()).or_default();

        // Clean old entries outside momentum window
        let cutoff = now - chrono::Duration::seconds(self.config.momentum_window_secs as i64);
        previous.retain(|s| s.recorded_at >= cutoff);

        // Detect shift if we have a prior snapshot
        let signal = if let Some(last) = previous.last() {
            self.detect_shift(last, &line, now)
        } else {
            None
        };

        previous.push(snapshot);

        // Enforce max history per key
        if previous.len() > 1000 {
            previous.drain(0..previous.len() - 500);
        }

        signal
    }

    /// Core shift detection logic.
    fn detect_shift(
        &mut self,
        previous: &OddsSnapshot,
        current: &OddsLine,
        now: DateTime<Utc>,
    ) -> Option<TradeSignal> {
        let prev_odds = previous.line.odds;
        let curr_odds = current.odds;

        if prev_odds.is_zero() || curr_odds.is_zero() {
            warn!("Zero odds detected — skipping signal generation");
            return None;
        }

        // Calculate shift in basis points (1 bp = 0.0001 = 0.01%)
        // shift_bps = |(current - previous) / previous| * 10000
        let delta = curr_odds - prev_odds;
        let abs_delta = delta.abs();
        let shift_bps = (abs_delta / prev_odds * Decimal::from(10000u32))
            .round()
            .to_u32()
            .unwrap_or(0);

        let direction = if delta > Decimal::ZERO {
            ShiftDirection::Up
        } else if delta < Decimal::ZERO {
            ShiftDirection::Down
        } else {
            ShiftDirection::Stable
        };

        // Check against market-specific significance threshold
        let significance_threshold = current.market_type.significance_threshold_bps();
        let severity = classify_severity(shift_bps, significance_threshold);

        if severity == ShiftSeverity::Minor && shift_bps < self.config.min_shift_bps {
            debug!(
                match_id=%current.match_id, market=?current.market_type,
                outcome=%current.outcome, shift_bps,
                "Shift below minimum threshold — no signal"
            );
            return None;
        }

        // Cooldown check
        let cooldown_key = Self::history_key(&current.match_id, current.market_type, &current.outcome);
        if let Some(last_signal_time) = self.recent_signals.get(&cooldown_key) {
            let elapsed = (now - *last_signal_time).num_seconds();
            if elapsed < self.config.cooldown_secs as i64 {
                debug!(match_id=%current.match_id, elapsed, "Cooldown active — suppressing signal");
                return None;
            }
        }

        // Check for reversal (odds swung opposite direction after a recent signal)
        if let Some(last_signal_time) = self.recent_signals.get(&cooldown_key) {
            let reversal_bps = (delta.abs() / prev_odds * Decimal::from(10000u32))
                .round()
                .to_u32()
                .unwrap_or(0);
            if reversal_bps >= self.config.reversal_threshold_bps
                && (now - *last_signal_time).num_seconds() < self.config.cooldown_secs as i64 * 3
            {
                info!(
                    match_id=%current.match_id, reversal_bps,
                    "Odds reversal detected — potential mean reversion opportunity"
                );
                // Still emit the signal — reversal is itself a signal
            }
        }

        // Determine trade action: back on odds drop, lay on odds rise
        let action = match direction {
            ShiftDirection::Up => TradeAction::Lay,
            ShiftDirection::Down => TradeAction::Back,
            ShiftDirection::Stable => TradeAction::NoAction,
        };

        // Calculate confidence based on shift magnitude and market type
        let confidence = calculate_confidence(shift_bps, significance_threshold, &current.market_type);
        if confidence < self.config.min_confidence {
            debug!(confidence, min_confidence=%self.config.min_confidence, "Confidence below threshold");
            return None;
        }

        // Calculate recommended stake using Kelly-adjacent sizing
        let stake = self.calculate_stake(prev_odds, curr_odds, confidence);

        // Generate signal ID
        let signal_id = format!(
            "FAN-{}-{}-{}-{}",
            chrono::Utc::now().format("%Y%m%d%H%M%S"),
            &current.match_id[..current.match_id.len().min(6)],
            market_type_abbrev(current.market_type),
            uuid::Uuid::new_v4().to_string().split('-').next().unwrap_or("0")
        );

        let signal = TradeSignal {
            signal_id,
            match_id: current.match_id.clone(),
            market_type: current.market_type,
            outcome: current.outcome.clone(),
            action,
            odds: curr_odds,
            stake_recommendation: stake,
            confidence,
            trigger: SignalTrigger::SharpOddsShift {
                shift_bps,
                direction,
                previous_odds: prev_odds,
            },
            generated_at: now,
            expires_at: now + chrono::Duration::seconds(300), // 5-minute validity
            reasoning: format!(
                "{} shift of {} bps detected on {} market for outcome '{}'. \
                 Previous odds: {:.2}, current: {:.2}. Confidence: {:.1}%.",
                severity_label(severity), shift_bps,
                market_type_string(current.market_type),
                current.outcome, prev_odds, curr_odds,
                confidence * 100.0
            ),
        };

        // Record signal for cooldown
        self.recent_signals.insert(cooldown_key, now);

        info!(
            signal_id=%signal.signal_id, match_id=%current.match_id,
            action=?signal.action, odds=%curr_odds, confidence=%confidence,
            "Trade signal generated"
        );

        Some(signal)
    }

    /// Calculate recommended stake using a modified Kelly criterion approximation.
    /// stake = bankroll * fraction * confidence * edge_factor
    fn calculate_stake(
        &self,
        prev_odds: Decimal,
        curr_odds: Decimal,
        confidence: f64,
    ) -> Decimal {
        let edge_bps = ((curr_odds - prev_odds) / prev_odds * Decimal::from(10000u32))
            .abs()
            .round()
            .to_u32()
            .unwrap_or(0) as f64;

        // Edge factor: 0 at 0 bps, asymptoting to 1.0 at high bps
        let edge_factor = 1.0 - (-edge_bps / 50.0).exp();

        // Kelly fraction scaled by confidence and edge
        let kelly = self.config.max_stake_fraction.to_f64().unwrap_or(0.05) * confidence * edge_factor;

        // Clamp between 1% and max_stake_fraction of bankroll
        let clamped = kelly.clamp(0.01, self.config.max_stake_fraction.to_f64().unwrap_or(0.05));

        Decimal::from_f64_retain(clamped).unwrap_or(dec!(0.01))
    }

    /// Detect cross-market arbitrage signals by comparing odds across bookmakers
    /// for the same match/market/outcome.
    pub fn detect_arbitrage(
        &self,
        lines: &[OddsLine],
    ) -> Vec<TradeSignal> {
        if !self.config.enable_arbitrage {
            return vec![];
        }

        let mut signals = Vec::new();

        // Group by (match_id, market_type, outcome)
        let mut grouped: HashMap<String, Vec<&OddsLine>> = HashMap::new();
        for line in lines {
            let key = Self::history_key(&line.match_id, line.market_type, &line.outcome);
            grouped.entry(key).or_default().push(line);
        }

        for (_key, group) in grouped {
            if group.len() < 2 {
                continue;
            }

            // Find max and min odds across bookmakers
            let max_line = group
                .iter()
                .max_by(|a, b| a.odds.cmp(&b.odds))
                .unwrap();
            let min_line = group
                .iter()
                .min_by(|a, b| a.odds.cmp(&b.odds))
                .unwrap();

            let spread = max_line.odds - min_line.odds;
            if spread.is_zero() {
                continue;
            }

            let spread_bps = (spread / min_line.odds * Decimal::from(10000u32))
                .round()
                .to_u32()
                .unwrap_or(0);

            // Arbitrage threshold: >50 bps spread is actionable
            if spread_bps < 50 {
                continue;
            }

            let signal = TradeSignal {
                signal_id: format!("ARB-{}", uuid::Uuid::new_v4()),
                match_id: max_line.match_id.clone(),
                market_type: max_line.market_type,
                outcome: max_line.outcome.clone(),
                action: TradeAction::Back,
                odds: max_line.odds,
                stake_recommendation: dec!(0.03), // 3% on arb
                confidence: 0.85,
                trigger: SignalTrigger::CrossMarketArbitrage {
                    spread_bps,
                    best_odds: max_line.odds,
                    worst_odds: min_line.odds,
                    best_bookmaker: max_line.bookmaker.clone(),
                },
                generated_at: chrono::Utc::now(),
                expires_at: chrono::Utc::now() + chrono::Duration::seconds(120),
                reasoning: format!(
                    "Cross-market arbitrage: {} bps spread on {} {}. \
                     Best: {} @ {:.2}, Worst: {} @ {:.2}",
                    spread_bps, max_line.match_id, max_line.outcome,
                    max_line.bookmaker, max_line.odds,
                    min_line.bookmaker, min_line.odds
                ),
            };

            signals.push(signal);
        }

        signals
    }

    /// Detect momentum signals from historical odds trends.
    pub fn detect_momentum(&self, match_id: &str, market_type: MarketType) -> Option<f64> {
        let mut all_lines: Vec<&OddsSnapshot> = self
            .history
            .iter()
            .filter(|(k, _)| k.starts_with(match_id))
            .flat_map(|(_, v)| v.iter())
            .collect();

        if all_lines.len() < self.config.momentum_min_samples {
            return None;
        }

        all_lines.sort_by_key(|s| s.recorded_at);

        // Simple linear momentum: slope of odds over time
        let first = all_lines.first().unwrap();
        let last = all_lines.last().unwrap();
        let duration_secs = (last.recorded_at - first.recorded_at).num_seconds() as f64;

        if duration_secs < 1.0 {
            return None;
        }

        let odds_change = (last.line.odds - first.line.odds)
            .to_f64()
            .unwrap_or(0.0);
        let momentum = odds_change / duration_secs;

        Some(momentum)
    }

    /// Clear all internal state.
    pub fn reset(&mut self) {
        self.history.clear();
        self.recent_signals.clear();
    }

    /// Return current state size for monitoring.
    pub fn state_size(&self) -> (usize, usize) {
        (self.history.len(), self.recent_signals.len())
    }
}

impl Default for StrategyEngine {
    fn default() -> Self {
        Self::new()
    }
}

// ──────────────────────────────────────────────
// Signal Triggers
// ──────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SignalTrigger {
    #[serde(rename = "sharp_odds_shift")]
    SharpOddsShift {
        shift_bps: u32,
        direction: ShiftDirection,
        previous_odds: Decimal,
    },
    #[serde(rename = "cross_market_arbitrage")]
    CrossMarketArbitrage {
        spread_bps: u32,
        best_odds: Decimal,
        worst_odds: Decimal,
        best_bookmaker: String,
    },
    #[serde(rename = "momentum_breakout")]
    MomentumBreakout {
        momentum_score: f64,
        sample_count: usize,
    },
    #[serde(rename = "odds_reversal")]
    OddsReversal {
        reversal_bps: u32,
        original_direction: ShiftDirection,
    },
}

// ──────────────────────────────────────────────
// Helper Functions
// ──────────────────────────────────────────────

fn classify_severity(shift_bps: u32, threshold: u32) -> ShiftSeverity {
    if shift_bps >= threshold * 5 {
        ShiftSeverity::Critical
    } else if shift_bps >= threshold * 2 {
        ShiftSeverity::Significant
    } else if shift_bps >= threshold {
        ShiftSeverity::Notable
    } else {
        ShiftSeverity::Minor
    }
}

fn severity_label(severity: ShiftSeverity) -> &'static str {
    match severity {
        ShiftSeverity::Minor => "Minor",
        ShiftSeverity::Notable => "Notable",
        ShiftSeverity::Significant => "Significant",
        ShiftSeverity::Critical => "CRITICAL",
    }
}

fn calculate_confidence(shift_bps: u32, threshold: u32, _market_type: &MarketType) -> f64 {
    if shift_bps >= threshold * 10 {
        0.98
    } else if shift_bps >= threshold * 5 {
        0.90
    } else if shift_bps >= threshold * 2 {
        0.80
    } else if shift_bps >= threshold {
        0.67
    } else if shift_bps >= threshold / 2 {
        0.50
    } else {
        0.30
    }
}

fn market_type_string(mt: MarketType) -> &'static str {
    match mt {
        MarketType::MatchWinner => "match_winner",
        MarketType::TotalGoals => "total_goals",
        MarketType::BothTeamsToScore => "both_teams_to_score",
        MarketType::CorrectScore => "correct_score",
        MarketType::OverUnder25 => "over_under_2_5",
        MarketType::AsianHandicap => "asian_handicap",
        MarketType::FirstGoalScorer => "first_goal_scorer",
        MarketType::HalfTimeFullTime => "half_time_full_time",
    }
}

fn market_type_abbrev(mt: MarketType) -> &'static str {
    match mt {
        MarketType::MatchWinner => "MW",
        MarketType::TotalGoals => "TG",
        MarketType::BothTeamsToScore => "BTTS",
        MarketType::CorrectScore => "CS",
        MarketType::OverUnder25 => "OU25",
        MarketType::AsianHandicap => "AH",
        MarketType::FirstGoalScorer => "FGS",
        MarketType::HalfTimeFullTime => "HTFT",
    }
}

// ──────────────────────────────────────────────
// Tests
// ──────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_line(match_id: &str, market: MarketType, outcome: &str, odds: f64) -> OddsLine {
        OddsLine {
            match_id: match_id.into(),
            market_type: market,
            outcome: outcome.into(),
            odds: Decimal::from_f64_retain(odds).unwrap(),
            timestamp: chrono::Utc::now(),
            bookmaker: "TestBook".into(),
            signature: None,
        }
    }

    #[test]
    fn test_no_signal_on_first_ingest() {
        let mut engine = StrategyEngine::new();
        let line = make_line("WC2026-001", MarketType::MatchWinner, "TeamA", 2.10);
        let signal = engine.ingest(line);
        assert!(signal.is_none(), "First ingest should not trigger a signal");
    }

    #[test]
    fn test_signal_on_significant_shift() {
        let mut engine = StrategyEngine::new();
        let t1 = chrono::Utc::now();
        let t2 = t1 + chrono::Duration::seconds(30);

        let line1 = OddsLine {
            match_id: "WC2026-001".into(),
            market_type: MarketType::MatchWinner,
            outcome: "TeamA".into(),
            odds: dec!(2.50),
            timestamp: t1,
            bookmaker: "BookA".into(),
            signature: None,
        };
        engine.ingest(line1);

        let line2 = OddsLine {
            match_id: "WC2026-001".into(),
            market_type: MarketType::MatchWinner,
            outcome: "TeamA".into(),
            odds: dec!(2.00), // 20% drop = 2000 bps
            timestamp: t2,
            bookmaker: "BookA".into(),
            signature: None,
        };
        let signal = engine.ingest(line2);
        assert!(signal.is_some(), "Large shift should trigger signal");
        let s = signal.unwrap();
        assert_eq!(s.action, TradeAction::Back);
        assert!(s.confidence > 0.8);
    }

    #[test]
    fn test_cooldown_suppression() {
        let mut engine = StrategyEngine::new();
        let t = chrono::Utc::now();

        let line1 = OddsLine {
            match_id: "WC2026-002".into(),
            market_type: MarketType::AsianHandicap,
            outcome: "TeamB -1".into(),
            odds: dec!(1.95),
            timestamp: t,
            bookmaker: "BookA".into(),
            signature: None,
        };
        engine.ingest(line1);

        // Trigger signal with large shift
        let line2 = OddsLine {
            match_id: "WC2026-002".into(),
            market_type: MarketType::AsianHandicap,
            outcome: "TeamB -1".into(),
            odds: dec!(1.60),
            timestamp: t + chrono::Duration::seconds(10),
            bookmaker: "BookA".into(),
            signature: None,
        };
        let sig1 = engine.ingest(line2);
        assert!(sig1.is_some());

        // Immediate follow-up should be suppressed by cooldown
        let line3 = OddsLine {
            match_id: "WC2026-002".into(),
            market_type: MarketType::AsianHandicap,
            outcome: "TeamB -1".into(),
            odds: dec!(1.55),
            timestamp: t + chrono::Duration::seconds(15),
            bookmaker: "BookA".into(),
            signature: None,
        };
        let sig2 = engine.ingest(line3);
        assert!(sig2.is_none(), "Cooldown should suppress rapid signals");
    }

    #[test]
    fn test_shifts_below_threshold_no_signal() {
        let mut engine = StrategyEngine::new();
        let t = chrono::Utc::now();

        let line1 = OddsLine {
            match_id: "WC2026-003".into(),
            market_type: MarketType::OverUnder25,
            outcome: "Over".into(),
            odds: dec!(1.90),
            timestamp: t,
            bookmaker: "BookA".into(),
            signature: None,
        };
        engine.ingest(line1);

        // Tiny shift: 1.90 -> 1.91 = ~52 bps, above the 10 bps threshold but depends
        // Let's use a truly tiny one
        let line2 = OddsLine {
            match_id: "WC2026-003".into(),
            market_type: MarketType::OverUnder25,
            outcome: "Over".into(),
            odds: dec!(1.9005), // Tiny
            timestamp: t + chrono::Duration::seconds(30),
            bookmaker: "BookA".into(),
            signature: None,
        };
        let signal = engine.ingest(line2);
        assert!(signal.is_none(), "Miniscule shift below threshold");
    }

    #[test]
    fn test_arbitrage_detection() {
        let engine = StrategyEngine::new();
        let now = chrono::Utc::now();

        let lines = vec![
            OddsLine {
                match_id: "WC2026-ARB".into(),
                market_type: MarketType::MatchWinner,
                outcome: "Draw".into(),
                odds: dec!(3.50),
                timestamp: now,
                bookmaker: "BookHigh".into(),
                signature: None,
            },
            OddsLine {
                match_id: "WC2026-ARB".into(),
                market_type: MarketType::MatchWinner,
                outcome: "Draw".into(),
                odds: dec!(2.80),
                timestamp: now,
                bookmaker: "BookLow".into(),
                signature: None,
            },
        ];

        let signals = engine.detect_arbitrage(&lines);
        // 0.70 spread on 2.80 base = 2500 bps — should trigger
        assert!(!signals.is_empty(), "Wide spread should trigger arbitrage signal");
        let arb = &signals[0];
        assert_eq!(arb.action, TradeAction::Back);
        assert!(arb.confidence > 0.8);
    }

    #[test]
    fn test_momentum_insufficient_data() {
        let engine = StrategyEngine::new();
        let mom = engine.detect_momentum("WC2026-NODATA", MarketType::MatchWinner);
        assert!(mom.is_none(), "No data = no momentum");
    }

    #[test]
    fn test_state_size_tracking() {
        let mut engine = StrategyEngine::new();
        assert_eq!(engine.state_size(), (0, 0));

        let t = chrono::Utc::now();
        engine.ingest(OddsLine {
            match_id: "S1".into(),
            market_type: MarketType::MatchWinner,
            outcome: "X".into(),
            odds: dec!(2.0),
            timestamp: t,
            bookmaker: "B".into(),
            signature: None,
        });

        let (hist, _) = engine.state_size();
        assert_eq!(hist, 1, "One history entry after single ingest");
    }
}